
export const ADD_CART = 'add_cart'
export const DELETE_CART = 'delete_cart'
export const UPDATE_CART = 'update_cart'
export const COUNT_CART  = 'count_cart'
export const PREV_CART = 'prev_cart'
export const NEXT_CART = 'next_cart'
export const BLUR_CART = 'blur_cart'
export const CHECK_OUT = 'check_out'
export const DELETE_BILLS = 'delete_bills'